# 训练中的VecEnv配置
env_id: FlyCraft-V0
config_file: configs/env_configs/flycraft/env_config_for_sac_easy.json
train_env:
  num_process: 1
  seed: 3
  custom_config: 
    debug_mode: true
    flag_str: Train
evaluation_env:
  num_process: 16
  seed: 6
  custom_config:
    debug_mode: false
    flag_str: Evaluation
callback_env:
  num_process: 16
  seed: 7
  custom_config:
    debug_mode: false
    flag_str: Callback
env_str: flycraft