env_id: MyAntMaze_U_Diverse_G-v3
maze_map: [
  [1, 1, 1, 1, 1],
  [1, "r", "g", "g", 1],
  [1, 1, 1, "g", 1],
  [1, "g", "g", "g", 1],
  [1, 1, 1, 1, 1],
]
reward_type: sparse
continuing_task: false
env_str: my_antmaze_u