env_id: MyPointMaze_Large_Diverse_G-v3
maze_map: [
  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
  [1, "r", "g", "g", "g", 1, "g", "g", "g", "g", "g", 1],
  [1, "g", 1, 1, "g", 1, "g", 1, "g", 1, "g", 1],
  [1, "g", "g", "g", "g", "g", "g", 1, "g", "g", "g", 1],
  [1, "g", 1, 1, 1, 1, "g", 1, 1, 1, "g", 1],
  [1, "g", "g", 1, "g", 1, "g", "g", "g", "g", "g", 1],
  [1, 1, "g", 1, "g", 1, "g", 1, "g", 1, 1, 1],
  [1, "g", "g", 1, "g", "g", "g", 1, "g", "g", "g", 1],
  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
]
reward_type: dense
continuing_task: false
env_str: my_pointmaze_dense