defaults:
  - algo: sac_for_flycraft
  - env: flycraft_for_sac  # my_reach_for_sac
  - callback: sac
  - evaluate: flycraft
  - _self_

experiment_name: ???
train_steps: 1e6
ckpt_path: checkpoints/${env.env_str}/${experiment_name}
log_path: logs/${env.env_str}/${experiment_name}